-- Generado por import-food-images.mjs (2026-09-02T22:33:37.128Z)
update public.foods set image_url = '/foods/aceite-de-oliva.jpg' where name = 'Aceite de oliva';
update public.foods set image_url = '/foods/aguacate.jpg' where name = 'Aguacate';
update public.foods set image_url = '/foods/arroz-blanco-cocido.jpg' where name = 'Arroz blanco cocido';
update public.foods set image_url = '/foods/atun-en-agua.jpg' where name = 'Atún en agua';
update public.foods set image_url = '/foods/avena.jpg' where name = 'Avena';
update public.foods set image_url = '/foods/banano.jpg' where name = 'Banano';
update public.foods set image_url = '/foods/batata.jpg' where name = 'Batata';
update public.foods set image_url = '/foods/bistec-de-res.jpg' where name = 'Bistec de res';
update public.foods set image_url = '/foods/brocoli.jpg' where name = 'Brocoli';
update public.foods set image_url = '/foods/camarones.jpg' where name = 'Camarones';
update public.foods set image_url = '/foods/carne-molida-90.jpg' where name = 'Carne molida 90%';
update public.foods set image_url = '/foods/claras-de-huevo.jpg' where name = 'Claras de huevo';
update public.foods set image_url = '/foods/espinaca.jpg' where name = 'Espinaca';
update public.foods set image_url = '/foods/fresas.jpg' where name = 'Fresas';
update public.foods set image_url = '/foods/frijoles-negros.jpg' where name = 'Frijoles negros';
update public.foods set image_url = '/foods/garbanzos-cocidos.jpg' where name = 'Garbanzos cocidos';
update public.foods set image_url = '/foods/huevo.jpg' where name = 'Huevo';
update public.foods set image_url = '/foods/leche-entera.jpg' where name = 'Leche entera';
update public.foods set image_url = '/foods/lentejas-cocidas.jpg' where name = 'Lentejas cocidas';
update public.foods set image_url = '/foods/lomo-de-cerdo.jpg' where name = 'Lomo de cerdo';
update public.foods set image_url = '/foods/mani-sin-sal.jpg' where name = 'Maní sin sal';
update public.foods set image_url = '/foods/manzana.jpg' where name = 'Manzana';
update public.foods set image_url = '/foods/naranja.jpg' where name = 'Naranja';
update public.foods set image_url = '/foods/nueces.jpg' where name = 'Nueces';
update public.foods set image_url = '/foods/pan-integral.jpg' where name = 'Pan integral';
update public.foods set image_url = '/foods/papa.jpg' where name = 'Papa';
update public.foods set image_url = '/foods/pollo-pechuga.jpg' where name = 'Pollo pechuga';
update public.foods set image_url = '/foods/proteina-whey.jpg' where name = 'Proteína whey';
update public.foods set image_url = '/foods/queso-fresco.jpg' where name = 'Queso fresco';
update public.foods set image_url = '/foods/quinoa-cocida.jpg' where name = 'Quinoa cocida';
update public.foods set image_url = '/foods/salmon.jpg' where name = 'Salmón';
update public.foods set image_url = '/foods/tilapia.jpg' where name = 'Tilapia';
update public.foods set image_url = '/foods/tortilla-de-maiz.jpg' where name = 'Tortilla de maíz';
update public.foods set image_url = '/foods/yogur-natural.jpg' where name = 'Yogur natural';
