-- image_url en exercises + foods (idempotente, solo faltantes)
update public.exercises set image_url = '/exercises/barbell-squat.jpg' where id = 1;
update public.exercises set image_url = '/exercises/leg-press.jpg' where id = 2;
update public.exercises set image_url = '/exercises/hack-squat.jpg' where id = 3;
update public.exercises set image_url = '/exercises/barbell-deadlift.jpg' where id = 4;
update public.exercises set image_url = '/exercises/barbell-bench-press-medium-grip.jpg' where id = 5;
update public.exercises set image_url = '/exercises/incline-dumbbell-press.jpg' where id = 6;
update public.exercises set image_url = '/exercises/standing-military-press.jpg' where id = 7;
update public.exercises set image_url = '/exercises/side-lateral-raise.jpg' where id = 8;
update public.exercises set image_url = '/exercises/bent-over-barbell-row.jpg' where id = 9;
update public.exercises set image_url = '/exercises/chin-up.jpg' where id = 10;
update public.exercises set image_url = '/exercises/wide-grip-lat-pulldown.jpg' where id = 11;
update public.exercises set image_url = '/exercises/face-pull.jpg' where id = 12;
update public.exercises set image_url = '/exercises/barbell-curl.jpg' where id = 13;
update public.exercises set image_url = '/exercises/hammer-curls.jpg' where id = 14;
update public.exercises set image_url = '/exercises/triceps-pushdown.jpg' where id = 15;
update public.exercises set image_url = '/exercises/parallel-bar-dip.jpg' where id = 16;
update public.exercises set image_url = '/exercises/dumbbell-lunges.jpg' where id = 17;
update public.exercises set image_url = '/exercises/standing-dumbbell-calf-raise.jpg' where id = 18;
update public.exercises set image_url = '/exercises/plank.jpg' where id = 19;
update public.exercises set image_url = '/exercises/ab-roller.jpg' where id = 20;
update public.exercises set image_url = '/exercises/leg-extensions.jpg' where id = 22;
update public.exercises set image_url = '/exercises/lying-leg-curls.jpg' where id = 23;
update public.exercises set image_url = '/exercises/barbell-hip-thrust.jpg' where id = 24;
update public.exercises set image_url = '/exercises/romanian-deadlift.jpg' where id = 25;
update public.exercises set image_url = '/exercises/dumbbell-flyes.jpg' where id = 26;
update public.exercises set image_url = '/exercises/barbell-incline-bench-press-medium-grip.jpg' where id = 27;
update public.exercises set image_url = '/exercises/seated-dumbbell-press.jpg' where id = 28;
update public.exercises set image_url = '/exercises/front-dumbbell-raise.jpg' where id = 29;
update public.exercises set image_url = '/exercises/one-arm-dumbbell-row.jpg' where id = 30;
update public.exercises set image_url = '/exercises/ez-bar-skullcrusher.jpg' where id = 31;

update public.foods set image_url = '/foods/aceite-de-oliva.jpg' where name = 'Aceite de oliva';
update public.foods set image_url = '/foods/aguacate.jpg' where name = 'Aguacate';
update public.foods set image_url = '/foods/arroz-blanco-cocido.jpg' where name = 'Arroz blanco cocido';
update public.foods set image_url = '/foods/atun-en-agua.jpg' where name = 'Atún en agua';
update public.foods set image_url = '/foods/avena.jpg' where name = 'Avena';
update public.foods set image_url = '/foods/banano.jpg' where name = 'Banano';
update public.foods set image_url = '/foods/batata.jpg' where name = 'Batata';
update public.foods set image_url = '/foods/bistec-de-res.jpg' where name = 'Bistec de res';
update public.foods set image_url = '/foods/brocoli.jpg' where name = 'Brocoli';
update public.foods set image_url = '/foods/camarones.jpg' where name = 'Camarones';
update public.foods set image_url = '/foods/carne-molida-90.jpg' where name = 'Carne molida 90%';
update public.foods set image_url = '/foods/claras-de-huevo.jpg' where name = 'Claras de huevo';
update public.foods set image_url = '/foods/espinaca.jpg' where name = 'Espinaca';
update public.foods set image_url = '/foods/fresas.jpg' where name = 'Fresas';
update public.foods set image_url = '/foods/frijoles-negros.jpg' where name = 'Frijoles negros';
update public.foods set image_url = '/foods/garbanzos-cocidos.jpg' where name = 'Garbanzos cocidos';
update public.foods set image_url = '/foods/huevo.jpg' where name = 'Huevo';
update public.foods set image_url = '/foods/leche-entera.jpg' where name = 'Leche entera';
update public.foods set image_url = '/foods/lentejas-cocidas.jpg' where name = 'Lentejas cocidas';
update public.foods set image_url = '/foods/lomo-de-cerdo.jpg' where name = 'Lomo de cerdo';
update public.foods set image_url = '/foods/mani-sin-sal.jpg' where name = 'Maní sin sal';
update public.foods set image_url = '/foods/manzana.jpg' where name = 'Manzana';
update public.foods set image_url = '/foods/naranja.jpg' where name = 'Naranja';
update public.foods set image_url = '/foods/nueces.jpg' where name = 'Nueces';
update public.foods set image_url = '/foods/pan-integral.jpg' where name = 'Pan integral';
update public.foods set image_url = '/foods/papa.jpg' where name = 'Papa';
update public.foods set image_url = '/foods/pollo-pechuga.jpg' where name = 'Pollo pechuga';
update public.foods set image_url = '/foods/proteina-whey.jpg' where name = 'Proteína whey';
update public.foods set image_url = '/foods/queso-fresco.jpg' where name = 'Queso fresco';
update public.foods set image_url = '/foods/quinoa-cocida.jpg' where name = 'Quinoa cocida';
update public.foods set image_url = '/foods/salmon.jpg' where name = 'Salmón';
update public.foods set image_url = '/foods/tilapia.jpg' where name = 'Tilapia';
update public.foods set image_url = '/foods/tortilla-de-maiz.jpg' where name = 'Tortilla de maíz';
update public.foods set image_url = '/foods/yogur-natural.jpg' where name = 'Yogur natural';
